apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent 
          volumeMounts:
            - mountPath: /data/postgres
              name: data
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-pwd-secret
        #  env:
        #  - name: POSTGRES_USER
        #    value: user
        #  - name: POSTGRES_PASSWORD
        #    value: password
        #  - name: POSTGRES_DB
        #    value: userdb
      #volumes:
      #  - name: data
      #    emptyDir:
      #      sizeLimit: 100Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dbpvc
