apiVersion: v1
kind: Service
metadata:
  name: engine-service
  namespace: postgres
spec:
  selector:
    app: engine
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30099
