apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sfs-postgres 
spec:
  selector:
    matchLabels:
      app: postgres # has to match .spec.template.metadata.labels
#  serviceName: "postgres"
  replicas: 1 # by default is 1
#  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: postgres # has to match .spec.selector.matchLabels
    spec:
#      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /data/postgres
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 100Mi
