apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: engine
  replicas: 1
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
        - name: engine
          image: symmetrical-engine-app:latest
          imagePullPolicy: Never 
            #volumeMounts:
            #- mountPath: /data/postgres
            #  name: data
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: engine-pwd-secret
        #  env:
        #  - name: POSTGRES_USER
        #    value: user
        #  - name: POSTGRES_PASSWORD
        #    value: password
        #  - name: POSTGRES_DB
        #    value: userdb
        #volumes:
        #  - name: data
        # emptyDir:
        #      sizeLimit: 100Mi
