apiVersion: v1
kind: Secret
metadata:
  name: engine-pwd-secret
  namespace: postgres
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://dbservice:5432/userdb
  SPRING_DATASOURCE_USER: user
  SPRING_DATASOURCE_PASSWORD: password

